branches:
  only:
    - master

# Do not build on tags (GitHub only)
skip_tags: true

#faster cloning
clone_depth: 1

build: off

# Install the latest nightly of ChefDK
install:
  - ps: iex (irm https://omnitruck.chef.io/install.ps1); Install-Project -Project chefdk -channel current 
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - ps: c:\opscode\chefdk\bin\chef.bat shell-init powershell | iex; cmd /c c:\opscode\chefdk\bin\chef.bat --version
  - c:\opscode\chefdk\bin\chef.bat exec ruby --version
  - c:\opscode\chefdk\bin\chef.bat gem install chef-sugar

test_script:
  - c:\opscode\chefdk\bin\chef.bat exec rubocop --version
  - c:\opscode\chefdk\bin\chef.bat exec foodcritic --version
  - c:\opscode\chefdk\bin\chef.bat exec rake style
  - c:\opscode\chefdk\bin\chef.bat exec rake spec

deploy: off
