name 'awesome_customers_ubuntu'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures awesome_customers_ubuntu'
long_description 'Installs/Configures awesome_customers_ubuntu'
version '0.1.0'

depends 'apt', '~> 4.0.2'
depends 'firewall', '~> 2.5.2'
depends 'httpd', '~> 0.4.0'
depends 'mysql', '~> 8.0.2'
